; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno] ; Configuration for Arduino Uno environment
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM4 ; rodrigoacc10 remote Windows port 
;upload_port = /dev/cu.usbserial-120 ; lruizv remote Linux port 
test_framework = unity
test_build_src = yes       ; <-- This tells PIO to also build files in src/

;[env:native] ; Define a 'native' environment for running on the host machine
;platform = native ; Use the native platform (for unit tests and simulation)
;build_type = debug ; Build type set to debug for better diagnostics during testing
;test_framework = unity ; Use Unity as the test framework
;test_build_src = yes       ; <-- This tells PIO to also build files in src/