; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno] ; Configuration for Arduino Uno environment
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = COM4 ; rodrigoacc10 remote Windows port 
test_framework = unity
;lib_deps = throwtheswitch/Unity@^2.6.0 ; Unity library dependency
test_build_src = yes       ; <-- This tells PIO to also build files in src/
test_filter = test_hardware/test_lcd , test_hardware/test_main , test_hardware/test_servo ; Filter to run only the HW tests
test_ignore = test_logic ; Ignore logic tests in this environment

[env:uno_lrv] ; Configuration for Arduino Uno environment
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-1320 ; lruizv remote Linux port 
test_framework = unity
;lib_deps = throwtheswitch/Unity@^2.6.0 ; Unity library dependency
test_build_src = yes       ; <-- This tells PIO to also build files in src/
test_filter = test_hardware/test_lcd , test_hardware/test_main , test_hardware/test_servo ; Filter to run only the HW tests
test_ignore = test_logic ; Ignore logic tests in this environment

[env:native] ; Define a 'native' environment for running on the host machine
platform = native ; Use the native platform (for unit tests and simulation)
test_framework = googletest ; Use Google Test framework
;lib_deps = google/googletest@^1.14.0 ; Google Test library dependency
test_filter = test_logic ; Filter to run only the logic tests
test_ignore = test_hardware , test_hardware/test_lcd , test_hardware/test_main , test_hardware/test_servo ; Ignore hardware tests in this environment
